name: Testing and Analysis
on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string

jobs:
  run:
    runs-on: ${{ inputs.runs_on }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Flutter
      if: ${{ inputs.runs_on != 'self-hosted' }}      
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Check formatting
      run: flutter format --set-exit-if-changed --dry-run .
    
    - name: Run static analysis
      run: flutter analyze --no-fatal-infos .

    - name: Run machine tests
      run: |
        flutter test --machine test

    - name: Run tests
      run: |
        flutter test

    # - name: Run golden tests
    #   run: |
    #     flutter test --tags=golden

    - name: Run coverage
      run: |
        flutter test --coverage
        bash <(curl -s https://codecov.io/bash)

    # - name: Coveralls # TODO: Add this when we are ready
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     path-to-lcov: coverage/lcov.info